<?php

namespace ContainerTW5Bdxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ByKy6gyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.byKy6gy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.byKy6gy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ficheFrais' => ['privates', '.errored..service_locator.byKy6gy.App\\Entity\\FicheFrais', NULL, 'Cannot autowire service ".service_locator.byKy6gy": it references class "App\\Entity\\FicheFrais" but no such service exists.'],
            'ligneFraisForfaitRepository' => ['privates', 'App\\Repository\\LigneFraisForfaitRepository', 'getLigneFraisForfaitRepositoryService', true],
        ], [
            'ficheFrais' => 'App\\Entity\\FicheFrais',
            'ligneFraisForfaitRepository' => 'App\\Repository\\LigneFraisForfaitRepository',
        ]);
    }
}
