<?php

namespace ContainerTW5Bdxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheFrais2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.byKy6gy.App\Entity\FicheFrais' shared service.
     *
     * @return \App\Entity\FicheFrais
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.byKy6gy": it references class "App\\Entity\\FicheFrais" but no such service exists.');
    }
}
