<?php

namespace ContainerTW5Bdxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRolesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\RolesType' shared autowired service.
     *
     * @return \App\Form\Type\RolesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/RolesType.php';

        return $container->privates['App\\Form\\Type\\RolesType'] = new \App\Form\Type\RolesType();
    }
}
