<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FicheFrais extends \App\Entity\FicheFrais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'mois', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'nbJustificatifs', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'dateModif', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'user', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisForfait', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'lignesFraisHorsForfait', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'motifRefus'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'mois', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'nbJustificatifs', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'dateModif', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'user', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisForfait', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'lignesFraisHorsForfait', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'motifRefus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FicheFrais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMotifRefus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotifRefus', []);

        return parent::getMotifRefus();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotifRefus($motifRefus): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotifRefus', [$motifRefus]);

        parent::setMotifRefus($motifRefus);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?\App\Entity\Etat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(?\App\Entity\Etat $etat): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMois(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMois', []);

        return parent::getMois();
    }

    /**
     * {@inheritDoc}
     */
    public function setMois(?\DateTime $mois): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMois', [$mois]);

        return parent::setMois($mois);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJustificatifs(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJustificatifs', []);

        return parent::getNbJustificatifs();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJustificatifs(?int $nbJustificatifs): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJustificatifs', [$nbJustificatifs]);

        return parent::setNbJustificatifs($nbJustificatifs);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantValide(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantValide', []);

        return parent::getMontantValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantValide(?string $montantValide): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantValide', [$montantValide]);

        return parent::setMontantValide($montantValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', []);

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif(?\DateTimeInterface $dateModif): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', [$dateModif]);

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getLignesFraisForfait(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLignesFraisForfait', []);

        return parent::getLignesFraisForfait();
    }

    /**
     * {@inheritDoc}
     */
    public function addLignesFraisForfait(\App\Entity\LigneFraisForfait $lignesFraisForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLignesFraisForfait', [$lignesFraisForfait]);

        return parent::addLignesFraisForfait($lignesFraisForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLignesFraisForfait(\App\Entity\LigneFraisForfait $lignesFraisForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLignesFraisForfait', [$lignesFraisForfait]);

        return parent::removeLignesFraisForfait($lignesFraisForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function getLignesFraisHorsForfait(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLignesFraisHorsForfait', []);

        return parent::getLignesFraisHorsForfait();
    }

    /**
     * {@inheritDoc}
     */
    public function addLignesFraisHorsForfait(\App\Entity\LigneFraisHorsForfait $lignesFraisHorsForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLignesFraisHorsForfait', [$lignesFraisHorsForfait]);

        return parent::addLignesFraisHorsForfait($lignesFraisHorsForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLignesFraisHorsForfait(\App\Entity\LigneFraisHorsForfait $lignesFraisHorsForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLignesFraisHorsForfait', [$lignesFraisHorsForfait]);

        return parent::removeLignesFraisHorsForfait($lignesFraisHorsForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
